# Exclude all documentation
path-exclude /usr/share/doc/*
# but keep copyright files for compliance
path-include /usr/share/doc/*/copyright
# Exclude all man pages and info pages
path-exclude /usr/share/man/*
path-exclude /usr/share/info/*
# Exclude non-English dictionaries
path-exclude /usr/share/dict/wordlist.de*
