#!/bin/bash
echo "========================================="
echo "3D Reconstruction Tools"
echo "========================================="
echo ""
echo "COLMAP (Structure from Motion):"
colmap -h 2>&1 | head -5
echo ""
echo "Features:"
echo "  • CUDA-accelerated feature matching"
echo "  • OpenMP parallelization"
echo "  • Qt5 GUI viewer"
echo "  • CGAL meshing support"
echo ""
echo "Usage:"
echo "  colmap gui                    # Launch GUI"
echo "  colmap automatic_reconstructor # Auto pipeline"
echo "  colmap feature_extractor      # Extract features"
echo ""
echo "Open3D (Point Cloud Processing):"
python3 -c "import open3d; print(f'Version: {open3d.__version__}')" 2>/dev/null || echo "Python module: Install via pip"
echo ""
echo "Features:"
echo "  • Point cloud visualization"
echo "  • Mesh processing"
echo "  • CUDA acceleration (if enabled)"
echo "  • Python + C++ API"
echo ""
echo "Usage (Python):"
echo "  import open3d as o3d"
echo "  pcd = o3d.io.read_point_cloud('file.ply')"
echo "  o3d.visualization.draw_geometries([pcd])"
echo ""
echo "ML Capabilities:"
echo "  • Open3D ML (PyTorch-based) is NOT included by default"
echo "  • To enable: Rebuild with -DBUILD_TORCH=ON (requires PyTorch)"
echo "  • See build log or documentation for enabling ML features"
echo ""
echo "Documentation:"
echo "  COLMAP: https://colmap.github.io/"
echo "  Open3D: http://www.open3d.org/"
echo "========================================="
