LD_LIBRARY_PATH="${OPENBLAS_INSTALL_PREFIX}/lib:\${LD_LIBRARY_PATH}"
PKG_CONFIG_PATH="${OPENBLAS_INSTALL_PREFIX}/lib/pkgconfig:\${PKG_CONFIG_PATH}"
OpenBLAS_DIR="${OPENBLAS_INSTALL_PREFIX}/lib/cmake/openblas"
CMAKE_PREFIX_PATH="${OPENBLAS_INSTALL_PREFIX}:\${CMAKE_PREFIX_PATH}"
